# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - CONDA_DEPENDENCIES='cython astropy sphinx'
        - PIP_DEPENDENCIES='cookiecutter gitpython'
        - EVENT_TYPE='pull_request push'

install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - cookiecutter --no-input ./ -o ../test
   - cd ../test/packagename
   - python setup.py egg_info
   - python setup.py build
   - python setup.py build_docs
